---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile.erb
  customize:
    memory: 512
    cpus: 1

provisioner:
  name: chef_zero
  chef_omnibus_url: http://xenlet.stu.neva.ru/install.sh
  require_chef_omnibus: true

platforms:
  - name: centos-7.0
    attributes:
      ip:
        rabbitmq: 172.28.128.12
        keystone: 172.28.128.13
        glance: 172.28.128.14
        cinder: 172.28.128.15 
        nova: 172.28.128.16
        neutron: 172.28.128.17
        swift-proxy: 172.28.128.18
        heat: 172.28.128.19
        ceilometer: 172.28.128.20
        sahara: 172.28.128.21
      creds:
        admin_password: mySuperSecret 
      libvirt:
        type: qemu
    data_bags_path: "test/integration/data_bags"

suites:
  - name: rabbit
    driver:
      vm_hostname: rabbit.testcloud.com
      network:
        - ["private_network", {ip: "172.28.128.12"}]
    run_list:
      - recipe[centos_cloud::rabbitmq-server]
  - name: keystone
    driver:
      vm_hostname: keystone.testcloud.com
      network:
        - ["private_network", {ip: "172.28.128.13"}]
    run_list:
      - recipe[centos_cloud::keystone]
  - name: cinder
    driver:
      attached_disks:
        - ["sdb.vmdk", "2048", "0", "1", "hdd"]
      vm_hostname: cinder.testcloud.com
      network:
        - ["private_network", {ip: "172.28.128.15"}]
    run_list:
      - recipe[centos_cloud::add_disk]
      - recipe[centos_cloud::cinder]
  - name: glance
    driver:
      vm_hostname: glance.testcloud.com
      network:
        - ["private_network", {ip: "172.28.128.14"}]
    run_list:
      - recipe[centos_cloud::glance]
  - name: nova
    driver:
      vm_hostname: nova.testcloud.com
      network:
        - ["private_network", {ip: "172.28.128.16"}]
    run_list:
      - recipe[centos_cloud::nova]
  - name: neutron
    driver:
      vm_hostname: neutron.testcloud.com
      network:
        - ["private_network", {ip: "172.28.128.17"}]
    run_list:
      - recipe[centos_cloud::neutron]
  - name: swift
    driver:
      vm_hostname: swift.testcloud.com
      network:
        - ["private_network", {ip: "172.28.128.18"}]
    run_list:
      - recipe[centos_cloud::swift-proxy]
  - name: heat
    driver:
      vm_hostname: heat.testcloud.com
      network:
        - ["private_network", {ip: "172.28.128.19"}]
    run_list:
      - recipe[centos_cloud::heat]
  - name: ceilometer
    driver:
      vm_hostname: ceilometer.testcloud.com
      network:
        - ["private_network", {ip: "172.28.128.20"}]
    run_list:
      - recipe[centos_cloud::ceilometer]
  - name: savana
    driver:
      vm_hostname: sahara.testcloud.com
      network:
        - ["private_network", {ip: "172.28.128.21"}]
    run_list:
      - recipe[centos_cloud::sahara]
  - name: compute
    driver:
      attached_disks:
        - ["sdb.vmdk", "2048", "0", "1", "hdd"]
      vm_hostname: compute.testcloud.com
      network:
        - ["private_network", {ip: "172.28.128.22"}]
    run_list:
      - recipe[centos_cloud::add_disk]  
      - recipe[centos_cloud::nova-compute]
      - recipe[centos_cloud::swift-node]
