---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_solo
  require_chef_omnibus: false

platforms:
  - name: centos-7.0
    driver:
      box: lamudi/centos-7.0
      box_url: https://vagrantcloud.com/lamudi/boxes/centos-7.0/versions/2/providers/virtualbox.box
    attributes:
      ip:
        controller: 172.28.128.4
      creds:
        admin_password: mySuperSecret 
    data_bags_path: "test/integration/data_bags"

suites:
  - name: controller
    driver:
      vm_hostname: controller.testcloud.com
      network:
        - ["private_network", {type: "dhcp"}]
    run_list:
      - recipe[openstack::default]
    attributes:
  - name: compute
    driver:
      vm_hostname: compute.testcloud.com
      network:
        - ["private_network", {type: "dhcp"}]
    run_list:
      - recipe[openstack::default]
    attributes:
