---
driver:
  name: vagrant
  vagrantfile_erb: Vagrantfile.erb
  customize:
    memory: 256
    cpus: 1

provisioner:
  name: chef_zero
  chef_omnibus_url: http://xenlet.stu.neva.ru/install.sh
  require_chef_omnibus: true

platforms:
  - name: centos-7.0
    attributes:
      ip:
        rabbitmq: 198.18.0.12
        keystone: 198.18.0.13
        cinder: 198.18.0.14
        glance: 198.18.0.15
        nova: 198.18.0.16
        neutron: 198.18.0.17
        swift-proxy: 198.18.0.18
        heat: 198.18.0.19
        ceilometer: 198.18.0.20
        sahara: 198.18.0.21
      ip_ex:
        rabbitmq: 240.18.0.12
        keystone: 240.18.0.13
        cinder: 240.18.0.14
        glance: 240.18.0.15
        nova: 240.18.0.16
        neutron: 240.18.0.17
        swift-proxy: 240.18.0.18
        heat: 240.18.0.19
        ceilometer: 240.18.0.20
        sahara: 240.18.0.21
      creds:
        admin_password: mySuperSecret 
      libvirt:
        type: qemu
    data_bags_path: "test/integration/data_bags"

suites:
  - name: main-rabbit
    driver:
      vm_hostname: rabbit.testcloud.com
      network:
        - ["private_network", {ip: "240.18.0.12"}]
        - ["private_network", {ip: "198.18.0.12",virtualbox__intnet: true}]
    attributes:
      auto:
        external_ip: "240.18.0.12"
        internal_ip: "198.18.0.12"
    run_list:
      - recipe[centos_cloud::rabbitmq-server]
  - name: main-keystone
    driver:
      vm_hostname: keystone.testcloud.com
      network:
        - ["private_network", {ip: "240.18.0.13"}]
        - ["private_network", {ip: "198.18.0.13",virtualbox__intnet: true}]
    attributes:
      auto:
        external_ip: "240.18.0.13"
        internal_ip: "198.18.0.13"
    run_list:
      - recipe[centos_cloud::keystone]
  - name: cinder
    driver:
      attached_disks:
        - ["sdb.vmdk", "2048", "0", "1", "hdd"]
      vm_hostname: cinder.testcloud.com
      network:
        - ["private_network", {ip: "240.18.0.14"}]
        - ["private_network", {ip: "198.18.0.14",virtualbox__intnet: true}]
    attributes:
      auto:
        external_ip: "240.18.0.14"
        internal_ip: "198.18.0.14"
    run_list:
      - recipe[centos_cloud::add_disk]
      - recipe[centos_cloud::cinder]
  - name: main-glance
    driver:
      vm_hostname: glance.testcloud.com
      network:
        - ["private_network", {ip: "240.18.0.15"}]
        - ["private_network", {ip: "198.18.0.15",virtualbox__intnet: true}]
    attributes:
      auto:
        external_ip: "240.18.0.15"
        internal_ip: "198.18.0.15"
    run_list:
      - recipe[centos_cloud::glance]
  - name: main-nova
    driver:
      customize:
        memory: 512
      vm_hostname: nova.testcloud.com
      network:
        - ["private_network", {ip: "240.18.0.16"}]
        - ["private_network", {ip: "198.18.0.16",virtualbox__intnet: true}]
    attributes:
      auto:
        external_ip: "240.18.0.16"
        internal_ip: "198.18.0.16"
    run_list:
      - recipe[centos_cloud::nova]
  - name: main-neutron
    driver:
      customize:
        memory: 512
      vm_hostname: neutron.testcloud.com
      network:
        - ["private_network", {ip: "240.18.0.17"}]
        - ["private_network", {ip: "198.18.0.17",virtualbox__intnet: true}]
    attributes:
      auto:
        external_ip: "240.18.0.17"
        internal_ip: "198.18.0.17"
    run_list:
      - recipe[centos_cloud::neutron]
  - name: swift
    driver:
      vm_hostname: swift.testcloud.com
      network:
        - ["private_network", {ip: "240.18.0.18"}]
        - ["private_network", {ip: "198.18.0.18",virtualbox__intnet: true}]
    attributes:
      auto:
        external_ip: "240.18.0.18"
        internal_ip: "198.18.0.18"
    run_list:
      - recipe[centos_cloud::swift-proxy]
  - name: heat
    driver:
      vm_hostname: heat.testcloud.com
      network:
        - ["private_network", {ip: "240.18.0.19"}]
        - ["private_network", {ip: "198.18.0.19",virtualbox__intnet: true}]
    attributes:
      auto:
        external_ip: "240.18.0.19"
        internal_ip: "198.18.0.19"
    run_list:
      - recipe[centos_cloud::heat]
  - name: ceilometer
    driver:
      vm_hostname: ceilometer.testcloud.com
      network:
        - ["private_network", {ip: "240.18.0.20"}]
        - ["private_network", {ip: "198.18.0.20",virtualbox__intnet: true}]
    attributes:
      auto:
        external_ip: "240.18.0.20"
        internal_ip: "198.18.0.20"
    run_list:
      - recipe[centos_cloud::ceilometer]
  - name: savana
    driver:
      vm_hostname: sahara.testcloud.com
      network:
        - ["private_network", {ip: "240.18.0.21"}]
        - ["private_network", {ip: "198.18.0.21",virtualbox__intnet: true}]
    attributes:
      auto:
        external_ip: "240.18.0.21"
        internal_ip: "198.18.0.21"
    run_list:
      - recipe[centos_cloud::sahara]
  - name: main-compute
    driver:
      customize:
        memory: 1024
      attached_disks:
        - ["sdb.vmdk", "2048", "0", "1", "hdd"]
      vm_hostname: compute.testcloud.com
      network:
        - ["private_network", {ip: "240.18.0.22"}]
        - ["private_network", {ip: "198.18.0.22",virtualbox__intnet: true}]
    attributes:
      auto:
        external_ip: "240.18.0.22"
        internal_ip: "198.18.0.22"
    run_list:
      - recipe[centos_cloud::add_disk]  
      - recipe[centos_cloud::nova-compute]
