---
driver:
  name: vagrant
  customize:
    memory: 4096
    cpus: 4

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: fedora-20
    attributes:
      ip:
        controller: 172.28.128.12
      creds:
        admin_password: mySuperSecret 
    data_bags_path: "test/integration/data_bags"

suites:
  - name: controller
    driver:
      vm_hostname: controller.testcloud.com
      network:
        - ["private_network", {ip: "172.28.128.12"}]
    run_list:
      - recipe[centos_cloud]
