Vagrant.configure("2") do |c|
  c.vm.box = "opscode-centos-7.0"
  c.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_centos-7.0_chef-provisionerless.box"
  c.vm.hostname = "controller.testcloud.com"
  c.vm.network(:private_network, {:ip=>"172.28.128.12"})
  c.vm.synced_folder ".", "/vagrant", disabled: true
  c.vm.provider :virtualbox do |p|
    p.customize ["modifyvm", :id, "--memory", "4096"]
    p.customize ["modifyvm", :id, "--cpus", "4"]
  end
end
